### ISSUE TITLE
Update cost and reverse cost values in edge table

### ISSUE THREAD

**Issue by vidhan13j07** [vidhan13j07/pgrouting#14]
![img_20170704_230911737](https://user-images.githubusercontent.com/10212325/27839325-076c8a9a-610e-11e7-9550-11deb6d9f2b1.jpg)

**Comment by cvvergara** [comment]
![upright](https://user-images.githubusercontent.com/5035290/27839726-2a9cf2c0-60b9-11e7-9332-b63302074cf2.jpg)
