### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by vidhan13j07** [vidhan13j07/pgrouting#17]
That would be a unit tests that you can do with the sampledata graph
once you SELECT * INTO lined_edge_table SELECT pgr_lineGraph(.......
without removing edges you execute a dijkstra and analyze results.
and make some sort of conversion of results on terms of lined_edge_table to terms of edge_table

**Comment by cvvergara** [comment]
@vidhan13j07 
make something similar to what I did in the chat, adjust to the chosen output
put it in the documentation of pgr_lineGraph
